# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
  - script: |
      choco install cppcheck
      mkdir build
      cd build
      cmake .. && cmake --build . && ctest -C Debug
    displayName: 'Build Advent Of Code Solutions in Debug mode'
  - script: |
      cd build
      cmake --build . --config Release && ctest -C Release
    displayName: 'Build Advent Of Code Solutions in Release mode'
